// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_thagt3a0YbdSIP4tYz87BVl1wkkkqs',
    appId: '1:564563276251:web:e14c19047d1e03caa3b7fe',
    messagingSenderId: '564563276251',
    projectId: 'messenger-3221b',
    authDomain: 'messenger-3221b.firebaseapp.com',
    storageBucket: 'messenger-3221b.appspot.com',
    measurementId: 'G-M4X6JBQLJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fQo3wVxBR6UqrczE893wSGn2DWPjHw4',
    appId: '1:564563276251:android:137634afad6455b7a3b7fe',
    messagingSenderId: '564563276251',
    projectId: 'messenger-3221b',
    storageBucket: 'messenger-3221b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XlCHvFD6JOmq6udMIhSS8Vlu0g5A87A',
    appId: '1:564563276251:ios:d71aa75d8a45db19a3b7fe',
    messagingSenderId: '564563276251',
    projectId: 'messenger-3221b',
    storageBucket: 'messenger-3221b.appspot.com',
    iosClientId: '564563276251-ipptpa9a9kh5lelao7u6a6o05jad4s9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2XlCHvFD6JOmq6udMIhSS8Vlu0g5A87A',
    appId: '1:564563276251:ios:d71aa75d8a45db19a3b7fe',
    messagingSenderId: '564563276251',
    projectId: 'messenger-3221b',
    storageBucket: 'messenger-3221b.appspot.com',
    iosClientId: '564563276251-ipptpa9a9kh5lelao7u6a6o05jad4s9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMessenger',
  );
}
